In [1]:
import pandas as pd

In [2]:
adult_info = pd.read_csv ('adult.csv')
adult_info

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
5,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
6,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
7,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
8,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
9,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
10,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
11,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
12,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
13,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
14,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
15,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
16,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
17,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
18,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
19,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
20,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
21,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
22,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
23,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
24,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
25,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
26,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
27,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
28,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
29,23,Local-gov,190709,Assoc-acdm,12,Never-married,Protective-serv,Not-in-family,White,Male,0,0,52,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32530,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
32531,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
32532,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
32533,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
32534,22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K
32535,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
32536,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K
32537,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32538,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32539,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
32540,41,?,202822,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K
32541,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K
32542,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
32543,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K
32544,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32545,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32546,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
32547,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32548,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32549,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32550,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32551,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
32552,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32553,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32554,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32555,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32556,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32557,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32558,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32559,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [3]:
#adding coloumn to df
adult_info['Siblings'] = 4

In [4]:
adult_info

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,siblings
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,4
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,4
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,4
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,4
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K,4
5,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K,4
6,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K,4
7,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K,4
8,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K,4
9,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K,4
10,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K,4
11,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K,4
12,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K,4
13,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K,4
14,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K,4
15,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K,4
16,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K,4
17,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K,4
18,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K,4
19,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K,4
20,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K,4
21,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K,4
22,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K,4
23,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K,4
24,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K,4
25,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K,4
26,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K,4
27,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K,4
28,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K,4
29,23,Local-gov,190709,Assoc-acdm,12,Never-married,Protective-serv,Not-in-family,White,Male,0,0,52,United-States,<=50K,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32530,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K,4
32531,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K,4
32532,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K,4
32533,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K,4
32534,22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K,4
32535,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K,4
32536,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K,4
32537,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K,4
32538,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K,4
32539,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K,4
32540,41,?,202822,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K,4
32541,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K,4
32542,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K,4
32543,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K,4
32544,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K,4
32545,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K,4
32546,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K,4
32547,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K,4
32548,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K,4
32549,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K,4
32550,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K,4
32551,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K,4
32552,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K,4
32553,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K,4
32554,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K,4
32555,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K,4
32556,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K,4
32557,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K,4
32558,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K,4
32559,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K,4

In [14]:
imdb_rating = pd.read_csv ('ratings.csv')
imdb_rating

,position,const,created,modified,description,Title,Title type,Directors,You rated,IMDb Rating,Runtime (mins),Year,Genres,Num. Votes,Release Date (month/day/year),URL
0,1,tt2872718,Sat Dec 31 00:00:00 2016,NaN,NaN,Nightcrawler,Feature Film,Dan Gilroy,8,7.9,117.0,2014,"crime, drama, thriller",311885,2014-09-05,http://www.imdb.com/title/tt2872718/
1,2,tt1260502,Fri Dec 30 00:00:00 2016,NaN,NaN,Ghost in the Shell 2.0,Feature Film,Mamoru Oshii,7,8.0,83.0,2008,"animation, action, crime, drama, sci_fi",10196,2008-07-12,http://www.imdb.com/title/tt1260502/
2,3,tt0944947,Fri Dec 30 00:00:00 2016,NaN,NaN,Game of Thrones,TV Series,NaN,10,9.5,56.0,2011,"adventure, drama, fantasy, romance",1095188,2011-04-17,http://www.imdb.com/title/tt0944947/
3,4,tt0367594,Fri Dec 30 00:00:00 2016,NaN,NaN,Charlie and the Chocolate Factory,Feature Film,Tim Burton,6,6.7,115.0,2005,"adventure, comedy, family, fantasy",331238,2005-07-10,http://www.imdb.com/title/tt0367594/
4,5,tt0317219,Fri Dec 30 00:00:00 2016,NaN,NaN,Cars,Feature Film,"John Lasseter, Joe Ranft",7,7.2,117.0,2006,"animation, adventure, comedy, family, sport",272829,2006-03-14,http://www.imdb.com/title/tt0317219/
5,6,tt1659337,Fri Dec 30 00:00:00 2016,NaN,NaN,The Perks of Being a Wallflower,Feature Film,Stephen Chbosky,8,8.0,102.0,2012,"drama, romance",363872,2012-09-08,http://www.imdb.com/title/tt1659337/
6,7,tt0097523,Fri Dec 30 00:00:00 2016,NaN,NaN,"Honey, I Shrunk the Kids",Feature Film,Joe Johnston,6,6.3,93.0,1989,"adventure, comedy, family, sci_fi",110477,1989-06-23,http://www.imdb.com/title/tt0097523/
7,8,tt0113497,Fri Dec 30 00:00:00 2016,NaN,NaN,Jumanji,Feature Film,Joe Johnston,6,6.9,104.0,1995,"action, adventure, family, fantasy, thriller",215299,1995-12-15,http://www.imdb.com/title/tt0113497/
8,9,tt0317705,Fri Dec 30 00:00:00 2016,NaN,NaN,The Incredibles,Feature Film,Brad Bird,8,8.0,115.0,2004,"animation, action, adventure, family",492831,2004-10-27,http://www.imdb.com/title/tt0317705/
9,10,tt0083866,Fri Dec 30 00:00:00 2016,NaN,NaN,E.T. the Extra-Terrestrial,Feature Film,Steven Spielberg,7,7.9,115.0,1982,"family, sci_fi",290317,1982-05-26,http://www.imdb.com/title/tt0083866/
10,11,tt0351283,Fri Dec 30 00:00:00 2016,NaN,NaN,Madagascar,Feature Film,"Eric Darnell, Tom McGrath",6,6.9,86.0,2005,"animation, adventure, comedy, family",275812,2005-05-25,http://www.imdb.com/title/tt0351283/
11,12,tt0102057,Fri Dec 30 00:00:00 2016,NaN,NaN,Hook,Feature Film,Steven Spielberg,6,6.7,142.0,1991,"adventure, comedy, family, fantasy",187300,1991-12-08,http://www.imdb.com/title/tt0102057/
12,13,tt0382932,Fri Dec 30 00:00:00 2016,NaN,NaN,Ratatouille,Feature Film,"Brad Bird, Jan Pinkava",7,8.0,111.0,2007,"animation, comedy, family, fantasy",488257,2007-06-22,http://www.imdb.com/title/tt0382932/
13,14,tt0113568,Fri Dec 30 00:00:00 2016,NaN,NaN,Ghost in the Shell,Feature Film,Mamoru Oshii,7,8.0,83.0,1995,"animation, action, mystery, sci_fi, thriller",84608,1995-11-18,http://www.imdb.com/title/tt0113568/
14,15,tt0107614,Fri Dec 30 00:00:00 2016,NaN,NaN,Mrs. Doubtfire,Feature Film,Chris Columbus,6,6.9,125.0,1993,"comedy, drama, family",187345,1993-11-24,http://www.imdb.com/title/tt0107614/
15,16,tt0268380,Fri Dec 30 00:00:00 2016,NaN,NaN,Ice Age,Feature Film,"Chris Wedge, Carlos Saldanha",8,7.6,81.0,2002,"animation, adventure, comedy, family",337365,2002-03-12,http://www.imdb.com/title/tt0268380/
16,17,tt3397884,Tue Dec 27 00:00:00 2016,NaN,NaN,Sicario,Feature Film,Denis Villeneuve,7,7.6,121.0,2015,"action, crime, drama, mystery, thriller",223005,2015-05-19,http://www.imdb.com/title/tt3397884/
17,18,tt0475784,Thu Dec 15 00:00:00 2016,NaN,NaN,Westworld,TV Series,Jonathan Nolan,8,9.1,60.0,2016,"drama, mystery, sci_fi, western",108687,2016-10-02,http://www.imdb.com/title/tt0475784/
18,19,tt1179933,Mon Dec 12 00:00:00 2016,NaN,NaN,10 Cloverfield Lane,Feature Film,Dan Trachtenberg,9,7.3,104.0,2016,"drama, horror, mystery, sci_fi, thriller",161240,2016-03-08,http://www.imdb.com/title/tt1179933/
19,20,tt1759761,Sun Dec 11 00:00:00 2016,NaN,NaN,Veep,TV Series,NaN,7,8.1,28.0,2012,comedy,26761,2012-04-22,http://www.imdb.com/title/tt1759761/
20,21,tt2543164,Tue Nov 29 00:00:00 2016,NaN,NaN,Arrival,Feature Film,Denis Villeneuve,8,8.3,116.0,2016,"drama, mystery, sci_fi, thriller",103756,2016-09-01,http://www.imdb.com/title/tt2543164/
21,22,tt5790504,Fri Nov 25 00:00:00 2016,NaN,NaN,Ein Mann unter Verdacht,TV Movie,Thomas Stuber,7,7.1,89.0,2016,crime,46,2016-06-24,http://www.imdb.com/title/tt5790504/
22,23,tt2543312,Tue Nov 8 00:00:00 2016,NaN,NaN,Halt and Catch Fire,TV Series,NaN,8,8.3,60.0,2014,drama,17185,2014-03-08,http://www.imdb.com/title/tt2543312/
23,24,tt0078748,Sun Nov 6 00:00:00 2016,NaN,NaN,Alien,Feature Film,Ridley Scott,9,8.5,117.0,1979,"horror, sci_fi",583893,1979-05-25,http://www.imdb.com/title/tt0078748/
24,25,tt1974419,Sat Nov 5 00:00:00 2016,NaN,NaN,The Neon Demon,Feature Film,Nicolas Winding Refn,4,6.3,118.0,2016,"horror, thriller",37285,2016-05-20,http://www.imdb.com/title/tt1974419/
25,26,tt1270798,Sat Nov 5 00:00:00 2016,NaN,NaN,X-Men: First Class,Feature Film,Matthew Vaughn,7,7.8,132.0,2011,"action, adventure, sci_fi",532310,2011-05-25,http://www.imdb.com/title/tt1270798/
26,27,tt2140479,Wed Nov 2 00:00:00 2016,NaN,NaN,The Accountant,Feature Film,Gavin O'Connor,8,7.5,128.0,2016,"action, crime, drama, thriller",72280,2016-10-10,http://www.imdb.com/title/tt2140479/
27,28,tt2085059,Sun Oct 23 00:00:00 2016,NaN,NaN,Black Mirror,TV Series,NaN,10,8.9,60.0,2011,"drama, sci_fi, thriller",93649,2011-12-04,http://www.imdb.com/title/tt2085059/
28,29,tt0112384,Sat Oct 22 00:00:00 2016,NaN,NaN,Apollo 13,Feature Film,Ron Howard,7,7.6,140.0,1995,"adventure, drama, history",214407,1995-06-22,http://www.imdb.com/title/tt0112384/
29,30,tt3385516,Tue Oct 18 00:00:00 2016,NaN,NaN,X-Men: Apocalypse,Feature Film,Bryan Singer,7,7.1,144.0,2016,"action, adventure, sci_fi",231116,2016-05-09,http://www.imdb.com/title/tt3385516/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479,480,tt1132620,Sun Jan 4 00:00:00 2015,NaN,NaN,The Girl with the Dragon Tattoo,Feature Film,Niels Arden Oplev,7,7.8,152.0,2009,"crime, drama, mystery, thriller",178180,2009-02-27,http://www.imdb.com/title/tt1132620/
480,481,tt0258000,Sun Jan 4 00:00:00 2015,NaN,NaN,Panic Room,Feature Film,David Fincher,7,6.8,112.0,2002,"crime, drama, thriller",210938,2002-03-18,http://www.imdb.com/title/tt0258000/
481,482,tt0123755,Sun Jan 4 00:00:00 2015,NaN,NaN,Cube,Feature Film,Vincenzo Natali,9,7.3,90.0,1997,"drama, mystery, sci_fi, thriller",165317,1997-09-09,http://www.imdb.com/title/tt0123755/
482,483,tt0944835,Sun Jan 4 00:00:00 2015,NaN,NaN,Salt,Feature Film,Phillip Noyce,6,6.4,100.0,2010,"action, crime, mystery, thriller",250555,2010-07-19,http://www.imdb.com/title/tt0944835/
483,484,tt0396171,Sun Jan 4 00:00:00 2015,NaN,NaN,Perfume: The Story of a Murderer,Feature Film,Tom Tykwer,7,7.5,147.0,2006,"crime, drama, fantasy",194910,2006-09-07,http://www.imdb.com/title/tt0396171/
484,485,tt0448134,Sun Jan 4 00:00:00 2015,NaN,NaN,Sunshine,Feature Film,Danny Boyle,8,7.3,107.0,2007,"adventure, sci_fi, thriller",194559,2007-03-23,http://www.imdb.com/title/tt0448134/
485,486,tt0250797,Sun Jan 4 00:00:00 2015,NaN,NaN,Unfaithful,Feature Film,Adrian Lyne,6,6.7,124.0,2002,"drama, thriller",64567,2002-05-08,http://www.imdb.com/title/tt0250797/
486,487,tt0230600,Sun Jan 4 00:00:00 2015,NaN,NaN,The Others,Feature Film,Alejandro Amenábar,6,7.6,101.0,2001,"horror, mystery, thriller",275571,2001-08-02,http://www.imdb.com/title/tt0230600/
487,488,tt0117381,Sun Jan 4 00:00:00 2015,NaN,NaN,Primal Fear,Feature Film,Gregory Hoblit,9,7.7,129.0,1996,"crime, drama, mystery, thriller",136381,1996-04-03,http://www.imdb.com/title/tt0117381/
488,489,tt1598778,Sun Jan 4 00:00:00 2015,NaN,NaN,Contagion,Feature Film,Steven Soderbergh,5,6.6,106.0,2011,"drama, thriller",183833,2011-09-03,http://www.imdb.com/title/tt1598778/
489,490,tt0497465,Sun Jan 4 00:00:00 2015,NaN,NaN,Vicky Cristina Barcelona,Feature Film,Woody Allen,6,7.2,96.0,2008,"drama, romance",203201,2008-05-17,http://www.imdb.com/title/tt0497465/
490,491,tt0309698,Sun Jan 4 00:00:00 2015,NaN,NaN,Identity,Feature Film,James Mangold,8,7.3,90.0,2003,"mystery, thriller",182644,2003-04-23,http://www.imdb.com/title/tt0309698/
491,492,tt0117060,Sun Jan 4 00:00:00 2015,NaN,NaN,Mission: Impossible,Feature Film,Brian De Palma,7,7.1,110.0,1996,"action, adventure, thriller",308458,1996-05-20,http://www.imdb.com/title/tt0117060/
492,493,tt1899353,Sun Jan 4 00:00:00 2015,NaN,NaN,The Raid: Redemption,Feature Film,Gareth Huw Evans,4,7.6,101.0,2011,"action, crime, thriller",152529,2011-09-08,http://www.imdb.com/title/tt1899353/
493,494,tt0079470,Sun Jan 4 00:00:00 2015,NaN,NaN,Life of Brian,Feature Film,Terry Jones,7,8.1,94.0,1979,comedy,280885,1979-08-17,http://www.imdb.com/title/tt0079470/
494,495,tt0095705,Sun Jan 4 00:00:00 2015,NaN,NaN,The Naked Gun: From the Files of Police Squad!,Feature Film,David Zucker,7,7.6,85.0,1988,"comedy, crime",117912,1988-12-02,http://www.imdb.com/title/tt0095705/
495,496,tt0063522,Sun Jan 4 00:00:00 2015,NaN,NaN,Rosemary's Baby,Feature Film,Roman Polanski,8,8.0,137.0,1968,"drama, horror",144870,1968-06-12,http://www.imdb.com/title/tt0063522/
496,497,tt2053463,Sun Jan 4 00:00:00 2015,NaN,NaN,Side Effects,Feature Film,Steven Soderbergh,7,7.1,106.0,2013,"crime, drama, thriller",151436,2013-01-31,http://www.imdb.com/title/tt2053463/
497,498,tt0421239,Sun Jan 4 00:00:00 2015,NaN,NaN,Red Eye,Feature Film,Wes Craven,6,6.5,85.0,2005,"mystery, thriller",95793,2005-08-04,http://www.imdb.com/title/tt0421239/
498,499,tt0181852,Sun Jan 4 00:00:00 2015,NaN,NaN,Terminator 3: Rise of the Machines,Feature Film,Jonathan Mostow,6,6.4,109.0,2003,"action, sci_fi",312324,2003-06-30,http://www.imdb.com/title/tt0181852/
499,500,tt0183649,Sun Jan 4 00:00:00 2015,NaN,NaN,Phone Booth,Feature Film,Joel Schumacher,9,7.1,81.0,2002,"crime, thriller",213136,2002-09-10,http://www.imdb.com/title/tt0183649/
500,501,tt0268126,Sun Jan 4 00:00:00 2015,NaN,NaN,Adaptation.,Feature Film,Spike Jonze,8,7.7,114.0,2002,"comedy, drama",146482,2002-12-06,http://www.imdb.com/title/tt0268126/
501,502,tt0195714,Sun Jan 4 00:00:00 2015,NaN,NaN,Final Destination,Feature Film,James Wong,6,6.7,98.0,2000,"horror, thriller",185492,2000-03-16,http://www.imdb.com/title/tt0195714/
502,503,tt0473705,Sun Jan 4 00:00:00 2015,NaN,NaN,State of Play,Feature Film,Kevin Macdonald,7,7.1,127.0,2009,"crime, drama, mystery, thriller",115342,2009-04-17,http://www.imdb.com/title/tt0473705/
503,504,tt1401152,Sun Jan 4 00:00:00 2015,NaN,NaN,Unknown,Feature Film,Jaume Collet-Serra,7,6.9,113.0,2011,"action, mystery, thriller",214477,2011-02-16,http://www.imdb.com/title/tt1401152/
504,505,tt0245712,Sun Jan 4 00:00:00 2015,NaN,NaN,Amores Perros,Feature Film,Alejandro González Iñárritu,7,8.1,154.0,2000,"drama, thriller",178506,2000-05-14,http://www.imdb.com/title/tt0245712/
505,506,tt2800240,Sun Jan 4 00:00:00 2015,NaN,NaN,Serial (Bad) Weddings,Feature Film,Philippe de Chauveron,7,7.0,97.0,2014,comedy,25603,2014-04-16,http://www.imdb.com/title/tt2800240/
506,507,tt0050825,Sun Jan 4 00:00:00 2015,NaN,NaN,Paths of Glory,Feature Film,Stanley Kubrick,8,8.5,88.0,1957,"drama, war",125510,1957-11-01,http://www.imdb.com/title/tt0050825/
507,508,tt0486822,Sun Jan 4 00:00:00 2015,NaN,NaN,Disturbia,Feature Film,D.J. Caruso,7,6.9,105.0,2007,"drama, mystery, thriller",190202,2007-04-04,http://www.imdb.com/title/tt0486822/
508,509,tt4176326,Sun Jan 4 00:00:00 2015,NaN,NaN,The Team,Documentary,"Martin Christ, Jens Gronheid",3,6.3,91.0,2014,"documentary, sport",1458,2014-11-11,http://www.imdb.com/title/tt4176326/

In [17]:
del imdb_rating ['const']
imdb_rating

,position,created,modified,description,Title,Title type,You rated,IMDb Rating,Runtime (mins),Year,Genres,Num. Votes,Release Date (month/day/year),URL
0,1,Sat Dec 31 00:00:00 2016,NaN,NaN,Nightcrawler,Feature Film,8,7.9,117.0,2014,"crime, drama, thriller",311885,2014-09-05,http://www.imdb.com/title/tt2872718/
1,2,Fri Dec 30 00:00:00 2016,NaN,NaN,Ghost in the Shell 2.0,Feature Film,7,8.0,83.0,2008,"animation, action, crime, drama, sci_fi",10196,2008-07-12,http://www.imdb.com/title/tt1260502/
2,3,Fri Dec 30 00:00:00 2016,NaN,NaN,Game of Thrones,TV Series,10,9.5,56.0,2011,"adventure, drama, fantasy, romance",1095188,2011-04-17,http://www.imdb.com/title/tt0944947/
3,4,Fri Dec 30 00:00:00 2016,NaN,NaN,Charlie and the Chocolate Factory,Feature Film,6,6.7,115.0,2005,"adventure, comedy, family, fantasy",331238,2005-07-10,http://www.imdb.com/title/tt0367594/
4,5,Fri Dec 30 00:00:00 2016,NaN,NaN,Cars,Feature Film,7,7.2,117.0,2006,"animation, adventure, comedy, family, sport",272829,2006-03-14,http://www.imdb.com/title/tt0317219/
5,6,Fri Dec 30 00:00:00 2016,NaN,NaN,The Perks of Being a Wallflower,Feature Film,8,8.0,102.0,2012,"drama, romance",363872,2012-09-08,http://www.imdb.com/title/tt1659337/
6,7,Fri Dec 30 00:00:00 2016,NaN,NaN,"Honey, I Shrunk the Kids",Feature Film,6,6.3,93.0,1989,"adventure, comedy, family, sci_fi",110477,1989-06-23,http://www.imdb.com/title/tt0097523/
7,8,Fri Dec 30 00:00:00 2016,NaN,NaN,Jumanji,Feature Film,6,6.9,104.0,1995,"action, adventure, family, fantasy, thriller",215299,1995-12-15,http://www.imdb.com/title/tt0113497/
8,9,Fri Dec 30 00:00:00 2016,NaN,NaN,The Incredibles,Feature Film,8,8.0,115.0,2004,"animation, action, adventure, family",492831,2004-10-27,http://www.imdb.com/title/tt0317705/
9,10,Fri Dec 30 00:00:00 2016,NaN,NaN,E.T. the Extra-Terrestrial,Feature Film,7,7.9,115.0,1982,"family, sci_fi",290317,1982-05-26,http://www.imdb.com/title/tt0083866/
10,11,Fri Dec 30 00:00:00 2016,NaN,NaN,Madagascar,Feature Film,6,6.9,86.0,2005,"animation, adventure, comedy, family",275812,2005-05-25,http://www.imdb.com/title/tt0351283/
11,12,Fri Dec 30 00:00:00 2016,NaN,NaN,Hook,Feature Film,6,6.7,142.0,1991,"adventure, comedy, family, fantasy",187300,1991-12-08,http://www.imdb.com/title/tt0102057/
12,13,Fri Dec 30 00:00:00 2016,NaN,NaN,Ratatouille,Feature Film,7,8.0,111.0,2007,"animation, comedy, family, fantasy",488257,2007-06-22,http://www.imdb.com/title/tt0382932/
13,14,Fri Dec 30 00:00:00 2016,NaN,NaN,Ghost in the Shell,Feature Film,7,8.0,83.0,1995,"animation, action, mystery, sci_fi, thriller",84608,1995-11-18,http://www.imdb.com/title/tt0113568/
14,15,Fri Dec 30 00:00:00 2016,NaN,NaN,Mrs. Doubtfire,Feature Film,6,6.9,125.0,1993,"comedy, drama, family",187345,1993-11-24,http://www.imdb.com/title/tt0107614/
15,16,Fri Dec 30 00:00:00 2016,NaN,NaN,Ice Age,Feature Film,8,7.6,81.0,2002,"animation, adventure, comedy, family",337365,2002-03-12,http://www.imdb.com/title/tt0268380/
16,17,Tue Dec 27 00:00:00 2016,NaN,NaN,Sicario,Feature Film,7,7.6,121.0,2015,"action, crime, drama, mystery, thriller",223005,2015-05-19,http://www.imdb.com/title/tt3397884/
17,18,Thu Dec 15 00:00:00 2016,NaN,NaN,Westworld,TV Series,8,9.1,60.0,2016,"drama, mystery, sci_fi, western",108687,2016-10-02,http://www.imdb.com/title/tt0475784/
18,19,Mon Dec 12 00:00:00 2016,NaN,NaN,10 Cloverfield Lane,Feature Film,9,7.3,104.0,2016,"drama, horror, mystery, sci_fi, thriller",161240,2016-03-08,http://www.imdb.com/title/tt1179933/
19,20,Sun Dec 11 00:00:00 2016,NaN,NaN,Veep,TV Series,7,8.1,28.0,2012,comedy,26761,2012-04-22,http://www.imdb.com/title/tt1759761/
20,21,Tue Nov 29 00:00:00 2016,NaN,NaN,Arrival,Feature Film,8,8.3,116.0,2016,"drama, mystery, sci_fi, thriller",103756,2016-09-01,http://www.imdb.com/title/tt2543164/
21,22,Fri Nov 25 00:00:00 2016,NaN,NaN,Ein Mann unter Verdacht,TV Movie,7,7.1,89.0,2016,crime,46,2016-06-24,http://www.imdb.com/title/tt5790504/
22,23,Tue Nov 8 00:00:00 2016,NaN,NaN,Halt and Catch Fire,TV Series,8,8.3,60.0,2014,drama,17185,2014-03-08,http://www.imdb.com/title/tt2543312/
23,24,Sun Nov 6 00:00:00 2016,NaN,NaN,Alien,Feature Film,9,8.5,117.0,1979,"horror, sci_fi",583893,1979-05-25,http://www.imdb.com/title/tt0078748/
24,25,Sat Nov 5 00:00:00 2016,NaN,NaN,The Neon Demon,Feature Film,4,6.3,118.0,2016,"horror, thriller",37285,2016-05-20,http://www.imdb.com/title/tt1974419/
25,26,Sat Nov 5 00:00:00 2016,NaN,NaN,X-Men: First Class,Feature Film,7,7.8,132.0,2011,"action, adventure, sci_fi",532310,2011-05-25,http://www.imdb.com/title/tt1270798/
26,27,Wed Nov 2 00:00:00 2016,NaN,NaN,The Accountant,Feature Film,8,7.5,128.0,2016,"action, crime, drama, thriller",72280,2016-10-10,http://www.imdb.com/title/tt2140479/
27,28,Sun Oct 23 00:00:00 2016,NaN,NaN,Black Mirror,TV Series,10,8.9,60.0,2011,"drama, sci_fi, thriller",93649,2011-12-04,http://www.imdb.com/title/tt2085059/
28,29,Sat Oct 22 00:00:00 2016,NaN,NaN,Apollo 13,Feature Film,7,7.6,140.0,1995,"adventure, drama, history",214407,1995-06-22,http://www.imdb.com/title/tt0112384/
29,30,Tue Oct 18 00:00:00 2016,NaN,NaN,X-Men: Apocalypse,Feature Film,7,7.1,144.0,2016,"action, adventure, sci_fi",231116,2016-05-09,http://www.imdb.com/title/tt3385516/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
479,480,Sun Jan 4 00:00:00 2015,NaN,NaN,The Girl with the Dragon Tattoo,Feature Film,7,7.8,152.0,2009,"crime, drama, mystery, thriller",178180,2009-02-27,http://www.imdb.com/title/tt1132620/
480,481,Sun Jan 4 00:00:00 2015,NaN,NaN,Panic Room,Feature Film,7,6.8,112.0,2002,"crime, drama, thriller",210938,2002-03-18,http://www.imdb.com/title/tt0258000/
481,482,Sun Jan 4 00:00:00 2015,NaN,NaN,Cube,Feature Film,9,7.3,90.0,1997,"drama, mystery, sci_fi, thriller",165317,1997-09-09,http://www.imdb.com/title/tt0123755/
482,483,Sun Jan 4 00:00:00 2015,NaN,NaN,Salt,Feature Film,6,6.4,100.0,2010,"action, crime, mystery, thriller",250555,2010-07-19,http://www.imdb.com/title/tt0944835/
483,484,Sun Jan 4 00:00:00 2015,NaN,NaN,Perfume: The Story of a Murderer,Feature Film,7,7.5,147.0,2006,"crime, drama, fantasy",194910,2006-09-07,http://www.imdb.com/title/tt0396171/
484,485,Sun Jan 4 00:00:00 2015,NaN,NaN,Sunshine,Feature Film,8,7.3,107.0,2007,"adventure, sci_fi, thriller",194559,2007-03-23,http://www.imdb.com/title/tt0448134/
485,486,Sun Jan 4 00:00:00 2015,NaN,NaN,Unfaithful,Feature Film,6,6.7,124.0,2002,"drama, thriller",64567,2002-05-08,http://www.imdb.com/title/tt0250797/
486,487,Sun Jan 4 00:00:00 2015,NaN,NaN,The Others,Feature Film,6,7.6,101.0,2001,"horror, mystery, thriller",275571,2001-08-02,http://www.imdb.com/title/tt0230600/
487,488,Sun Jan 4 00:00:00 2015,NaN,NaN,Primal Fear,Feature Film,9,7.7,129.0,1996,"crime, drama, mystery, thriller",136381,1996-04-03,http://www.imdb.com/title/tt0117381/
488,489,Sun Jan 4 00:00:00 2015,NaN,NaN,Contagion,Feature Film,5,6.6,106.0,2011,"drama, thriller",183833,2011-09-03,http://www.imdb.com/title/tt1598778/
489,490,Sun Jan 4 00:00:00 2015,NaN,NaN,Vicky Cristina Barcelona,Feature Film,6,7.2,96.0,2008,"drama, romance",203201,2008-05-17,http://www.imdb.com/title/tt0497465/
490,491,Sun Jan 4 00:00:00 2015,NaN,NaN,Identity,Feature Film,8,7.3,90.0,2003,"mystery, thriller",182644,2003-04-23,http://www.imdb.com/title/tt0309698/
491,492,Sun Jan 4 00:00:00 2015,NaN,NaN,Mission: Impossible,Feature Film,7,7.1,110.0,1996,"action, adventure, thriller",308458,1996-05-20,http://www.imdb.com/title/tt0117060/
492,493,Sun Jan 4 00:00:00 2015,NaN,NaN,The Raid: Redemption,Feature Film,4,7.6,101.0,2011,"action, crime, thriller",152529,2011-09-08,http://www.imdb.com/title/tt1899353/
493,494,Sun Jan 4 00:00:00 2015,NaN,NaN,Life of Brian,Feature Film,7,8.1,94.0,1979,comedy,280885,1979-08-17,http://www.imdb.com/title/tt0079470/
494,495,Sun Jan 4 00:00:00 2015,NaN,NaN,The Naked Gun: From the Files of Police Squad!,Feature Film,7,7.6,85.0,1988,"comedy, crime",117912,1988-12-02,http://www.imdb.com/title/tt0095705/
495,496,Sun Jan 4 00:00:00 2015,NaN,NaN,Rosemary's Baby,Feature Film,8,8.0,137.0,1968,"drama, horror",144870,1968-06-12,http://www.imdb.com/title/tt0063522/
496,497,Sun Jan 4 00:00:00 2015,NaN,NaN,Side Effects,Feature Film,7,7.1,106.0,2013,"crime, drama, thriller",151436,2013-01-31,http://www.imdb.com/title/tt2053463/
497,498,Sun Jan 4 00:00:00 2015,NaN,NaN,Red Eye,Feature Film,6,6.5,85.0,2005,"mystery, thriller",95793,2005-08-04,http://www.imdb.com/title/tt0421239/
498,499,Sun Jan 4 00:00:00 2015,NaN,NaN,Terminator 3: Rise of the Machines,Feature Film,6,6.4,109.0,2003,"action, sci_fi",312324,2003-06-30,http://www.imdb.com/title/tt0181852/
499,500,Sun Jan 4 00:00:00 2015,NaN,NaN,Phone Booth,Feature Film,9,7.1,81.0,2002,"crime, thriller",213136,2002-09-10,http://www.imdb.com/title/tt0183649/
500,501,Sun Jan 4 00:00:00 2015,NaN,NaN,Adaptation.,Feature Film,8,7.7,114.0,2002,"comedy, drama",146482,2002-12-06,http://www.imdb.com/title/tt0268126/
501,502,Sun Jan 4 00:00:00 2015,NaN,NaN,Final Destination,Feature Film,6,6.7,98.0,2000,"horror, thriller",185492,2000-03-16,http://www.imdb.com/title/tt0195714/
502,503,Sun Jan 4 00:00:00 2015,NaN,NaN,State of Play,Feature Film,7,7.1,127.0,2009,"crime, drama, mystery, thriller",115342,2009-04-17,http://www.imdb.com/title/tt0473705/
503,504,Sun Jan 4 00:00:00 2015,NaN,NaN,Unknown,Feature Film,7,6.9,113.0,2011,"action, mystery, thriller",214477,2011-02-16,http://www.imdb.com/title/tt1401152/
504,505,Sun Jan 4 00:00:00 2015,NaN,NaN,Amores Perros,Feature Film,7,8.1,154.0,2000,"drama, thriller",178506,2000-05-14,http://www.imdb.com/title/tt0245712/
505,506,Sun Jan 4 00:00:00 2015,NaN,NaN,Serial (Bad) Weddings,Feature Film,7,7.0,97.0,2014,comedy,25603,2014-04-16,http://www.imdb.com/title/tt2800240/
506,507,Sun Jan 4 00:00:00 2015,NaN,NaN,Paths of Glory,Feature Film,8,8.5,88.0,1957,"drama, war",125510,1957-11-01,http://www.imdb.com/title/tt0050825/
507,508,Sun Jan 4 00:00:00 2015,NaN,NaN,Disturbia,Feature Film,7,6.9,105.0,2007,"drama, mystery, thriller",190202,2007-04-04,http://www.imdb.com/title/tt0486822/
508,509,Sun Jan 4 00:00:00 2015,NaN,NaN,The Team,Documentary,3,6.3,91.0,2014,"documentary, sport",1458,2014-11-11,http://www.imdb.com/title/tt4176326/

In [18]:
#add row to df, make sure list matches columns
imdb_rating.loc[-1] = [9.4, 'Avengers:End Game', 'Action']
imdb_rating

ValueError: cannot set a row with mismatched columns

In [19]:
imdb_rating.index = imdb_rating.index + 1

In [20]:
imdb_rating = imdb_rating.sort_index()
imdb_rating

,position,created,modified,description,Title,Title type,You rated,IMDb Rating,Runtime (mins),Year,Genres,Num. Votes,Release Date (month/day/year),URL
1,1,Sat Dec 31 00:00:00 2016,NaN,NaN,Nightcrawler,Feature Film,8,7.9,117.0,2014,"crime, drama, thriller",311885,2014-09-05,http://www.imdb.com/title/tt2872718/
2,2,Fri Dec 30 00:00:00 2016,NaN,NaN,Ghost in the Shell 2.0,Feature Film,7,8.0,83.0,2008,"animation, action, crime, drama, sci_fi",10196,2008-07-12,http://www.imdb.com/title/tt1260502/
3,3,Fri Dec 30 00:00:00 2016,NaN,NaN,Game of Thrones,TV Series,10,9.5,56.0,2011,"adventure, drama, fantasy, romance",1095188,2011-04-17,http://www.imdb.com/title/tt0944947/
4,4,Fri Dec 30 00:00:00 2016,NaN,NaN,Charlie and the Chocolate Factory,Feature Film,6,6.7,115.0,2005,"adventure, comedy, family, fantasy",331238,2005-07-10,http://www.imdb.com/title/tt0367594/
5,5,Fri Dec 30 00:00:00 2016,NaN,NaN,Cars,Feature Film,7,7.2,117.0,2006,"animation, adventure, comedy, family, sport",272829,2006-03-14,http://www.imdb.com/title/tt0317219/
6,6,Fri Dec 30 00:00:00 2016,NaN,NaN,The Perks of Being a Wallflower,Feature Film,8,8.0,102.0,2012,"drama, romance",363872,2012-09-08,http://www.imdb.com/title/tt1659337/
7,7,Fri Dec 30 00:00:00 2016,NaN,NaN,"Honey, I Shrunk the Kids",Feature Film,6,6.3,93.0,1989,"adventure, comedy, family, sci_fi",110477,1989-06-23,http://www.imdb.com/title/tt0097523/
8,8,Fri Dec 30 00:00:00 2016,NaN,NaN,Jumanji,Feature Film,6,6.9,104.0,1995,"action, adventure, family, fantasy, thriller",215299,1995-12-15,http://www.imdb.com/title/tt0113497/
9,9,Fri Dec 30 00:00:00 2016,NaN,NaN,The Incredibles,Feature Film,8,8.0,115.0,2004,"animation, action, adventure, family",492831,2004-10-27,http://www.imdb.com/title/tt0317705/
10,10,Fri Dec 30 00:00:00 2016,NaN,NaN,E.T. the Extra-Terrestrial,Feature Film,7,7.9,115.0,1982,"family, sci_fi",290317,1982-05-26,http://www.imdb.com/title/tt0083866/
11,11,Fri Dec 30 00:00:00 2016,NaN,NaN,Madagascar,Feature Film,6,6.9,86.0,2005,"animation, adventure, comedy, family",275812,2005-05-25,http://www.imdb.com/title/tt0351283/
12,12,Fri Dec 30 00:00:00 2016,NaN,NaN,Hook,Feature Film,6,6.7,142.0,1991,"adventure, comedy, family, fantasy",187300,1991-12-08,http://www.imdb.com/title/tt0102057/
13,13,Fri Dec 30 00:00:00 2016,NaN,NaN,Ratatouille,Feature Film,7,8.0,111.0,2007,"animation, comedy, family, fantasy",488257,2007-06-22,http://www.imdb.com/title/tt0382932/
14,14,Fri Dec 30 00:00:00 2016,NaN,NaN,Ghost in the Shell,Feature Film,7,8.0,83.0,1995,"animation, action, mystery, sci_fi, thriller",84608,1995-11-18,http://www.imdb.com/title/tt0113568/
15,15,Fri Dec 30 00:00:00 2016,NaN,NaN,Mrs. Doubtfire,Feature Film,6,6.9,125.0,1993,"comedy, drama, family",187345,1993-11-24,http://www.imdb.com/title/tt0107614/
16,16,Fri Dec 30 00:00:00 2016,NaN,NaN,Ice Age,Feature Film,8,7.6,81.0,2002,"animation, adventure, comedy, family",337365,2002-03-12,http://www.imdb.com/title/tt0268380/
17,17,Tue Dec 27 00:00:00 2016,NaN,NaN,Sicario,Feature Film,7,7.6,121.0,2015,"action, crime, drama, mystery, thriller",223005,2015-05-19,http://www.imdb.com/title/tt3397884/
18,18,Thu Dec 15 00:00:00 2016,NaN,NaN,Westworld,TV Series,8,9.1,60.0,2016,"drama, mystery, sci_fi, western",108687,2016-10-02,http://www.imdb.com/title/tt0475784/
19,19,Mon Dec 12 00:00:00 2016,NaN,NaN,10 Cloverfield Lane,Feature Film,9,7.3,104.0,2016,"drama, horror, mystery, sci_fi, thriller",161240,2016-03-08,http://www.imdb.com/title/tt1179933/
20,20,Sun Dec 11 00:00:00 2016,NaN,NaN,Veep,TV Series,7,8.1,28.0,2012,comedy,26761,2012-04-22,http://www.imdb.com/title/tt1759761/
21,21,Tue Nov 29 00:00:00 2016,NaN,NaN,Arrival,Feature Film,8,8.3,116.0,2016,"drama, mystery, sci_fi, thriller",103756,2016-09-01,http://www.imdb.com/title/tt2543164/
22,22,Fri Nov 25 00:00:00 2016,NaN,NaN,Ein Mann unter Verdacht,TV Movie,7,7.1,89.0,2016,crime,46,2016-06-24,http://www.imdb.com/title/tt5790504/
23,23,Tue Nov 8 00:00:00 2016,NaN,NaN,Halt and Catch Fire,TV Series,8,8.3,60.0,2014,drama,17185,2014-03-08,http://www.imdb.com/title/tt2543312/
24,24,Sun Nov 6 00:00:00 2016,NaN,NaN,Alien,Feature Film,9,8.5,117.0,1979,"horror, sci_fi",583893,1979-05-25,http://www.imdb.com/title/tt0078748/
25,25,Sat Nov 5 00:00:00 2016,NaN,NaN,The Neon Demon,Feature Film,4,6.3,118.0,2016,"horror, thriller",37285,2016-05-20,http://www.imdb.com/title/tt1974419/
26,26,Sat Nov 5 00:00:00 2016,NaN,NaN,X-Men: First Class,Feature Film,7,7.8,132.0,2011,"action, adventure, sci_fi",532310,2011-05-25,http://www.imdb.com/title/tt1270798/
27,27,Wed Nov 2 00:00:00 2016,NaN,NaN,The Accountant,Feature Film,8,7.5,128.0,2016,"action, crime, drama, thriller",72280,2016-10-10,http://www.imdb.com/title/tt2140479/
28,28,Sun Oct 23 00:00:00 2016,NaN,NaN,Black Mirror,TV Series,10,8.9,60.0,2011,"drama, sci_fi, thriller",93649,2011-12-04,http://www.imdb.com/title/tt2085059/
29,29,Sat Oct 22 00:00:00 2016,NaN,NaN,Apollo 13,Feature Film,7,7.6,140.0,1995,"adventure, drama, history",214407,1995-06-22,http://www.imdb.com/title/tt0112384/
30,30,Tue Oct 18 00:00:00 2016,NaN,NaN,X-Men: Apocalypse,Feature Film,7,7.1,144.0,2016,"action, adventure, sci_fi",231116,2016-05-09,http://www.imdb.com/title/tt3385516/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
480,480,Sun Jan 4 00:00:00 2015,NaN,NaN,The Girl with the Dragon Tattoo,Feature Film,7,7.8,152.0,2009,"crime, drama, mystery, thriller",178180,2009-02-27,http://www.imdb.com/title/tt1132620/
481,481,Sun Jan 4 00:00:00 2015,NaN,NaN,Panic Room,Feature Film,7,6.8,112.0,2002,"crime, drama, thriller",210938,2002-03-18,http://www.imdb.com/title/tt0258000/
482,482,Sun Jan 4 00:00:00 2015,NaN,NaN,Cube,Feature Film,9,7.3,90.0,1997,"drama, mystery, sci_fi, thriller",165317,1997-09-09,http://www.imdb.com/title/tt0123755/
483,483,Sun Jan 4 00:00:00 2015,NaN,NaN,Salt,Feature Film,6,6.4,100.0,2010,"action, crime, mystery, thriller",250555,2010-07-19,http://www.imdb.com/title/tt0944835/
484,484,Sun Jan 4 00:00:00 2015,NaN,NaN,Perfume: The Story of a Murderer,Feature Film,7,7.5,147.0,2006,"crime, drama, fantasy",194910,2006-09-07,http://www.imdb.com/title/tt0396171/
485,485,Sun Jan 4 00:00:00 2015,NaN,NaN,Sunshine,Feature Film,8,7.3,107.0,2007,"adventure, sci_fi, thriller",194559,2007-03-23,http://www.imdb.com/title/tt0448134/
486,486,Sun Jan 4 00:00:00 2015,NaN,NaN,Unfaithful,Feature Film,6,6.7,124.0,2002,"drama, thriller",64567,2002-05-08,http://www.imdb.com/title/tt0250797/
487,487,Sun Jan 4 00:00:00 2015,NaN,NaN,The Others,Feature Film,6,7.6,101.0,2001,"horror, mystery, thriller",275571,2001-08-02,http://www.imdb.com/title/tt0230600/
488,488,Sun Jan 4 00:00:00 2015,NaN,NaN,Primal Fear,Feature Film,9,7.7,129.0,1996,"crime, drama, mystery, thriller",136381,1996-04-03,http://www.imdb.com/title/tt0117381/
489,489,Sun Jan 4 00:00:00 2015,NaN,NaN,Contagion,Feature Film,5,6.6,106.0,2011,"drama, thriller",183833,2011-09-03,http://www.imdb.com/title/tt1598778/
490,490,Sun Jan 4 00:00:00 2015,NaN,NaN,Vicky Cristina Barcelona,Feature Film,6,7.2,96.0,2008,"drama, romance",203201,2008-05-17,http://www.imdb.com/title/tt0497465/
491,491,Sun Jan 4 00:00:00 2015,NaN,NaN,Identity,Feature Film,8,7.3,90.0,2003,"mystery, thriller",182644,2003-04-23,http://www.imdb.com/title/tt0309698/
492,492,Sun Jan 4 00:00:00 2015,NaN,NaN,Mission: Impossible,Feature Film,7,7.1,110.0,1996,"action, adventure, thriller",308458,1996-05-20,http://www.imdb.com/title/tt0117060/
493,493,Sun Jan 4 00:00:00 2015,NaN,NaN,The Raid: Redemption,Feature Film,4,7.6,101.0,2011,"action, crime, thriller",152529,2011-09-08,http://www.imdb.com/title/tt1899353/
494,494,Sun Jan 4 00:00:00 2015,NaN,NaN,Life of Brian,Feature Film,7,8.1,94.0,1979,comedy,280885,1979-08-17,http://www.imdb.com/title/tt0079470/
495,495,Sun Jan 4 00:00:00 2015,NaN,NaN,The Naked Gun: From the Files of Police Squad!,Feature Film,7,7.6,85.0,1988,"comedy, crime",117912,1988-12-02,http://www.imdb.com/title/tt0095705/
496,496,Sun Jan 4 00:00:00 2015,NaN,NaN,Rosemary's Baby,Feature Film,8,8.0,137.0,1968,"drama, horror",144870,1968-06-12,http://www.imdb.com/title/tt0063522/
497,497,Sun Jan 4 00:00:00 2015,NaN,NaN,Side Effects,Feature Film,7,7.1,106.0,2013,"crime, drama, thriller",151436,2013-01-31,http://www.imdb.com/title/tt2053463/
498,498,Sun Jan 4 00:00:00 2015,NaN,NaN,Red Eye,Feature Film,6,6.5,85.0,2005,"mystery, thriller",95793,2005-08-04,http://www.imdb.com/title/tt0421239/
499,499,Sun Jan 4 00:00:00 2015,NaN,NaN,Terminator 3: Rise of the Machines,Feature Film,6,6.4,109.0,2003,"action, sci_fi",312324,2003-06-30,http://www.imdb.com/title/tt0181852/
500,500,Sun Jan 4 00:00:00 2015,NaN,NaN,Phone Booth,Feature Film,9,7.1,81.0,2002,"crime, thriller",213136,2002-09-10,http://www.imdb.com/title/tt0183649/
501,501,Sun Jan 4 00:00:00 2015,NaN,NaN,Adaptation.,Feature Film,8,7.7,114.0,2002,"comedy, drama",146482,2002-12-06,http://www.imdb.com/title/tt0268126/
502,502,Sun Jan 4 00:00:00 2015,NaN,NaN,Final Destination,Feature Film,6,6.7,98.0,2000,"horror, thriller",185492,2000-03-16,http://www.imdb.com/title/tt0195714/
503,503,Sun Jan 4 00:00:00 2015,NaN,NaN,State of Play,Feature Film,7,7.1,127.0,2009,"crime, drama, mystery, thriller",115342,2009-04-17,http://www.imdb.com/title/tt0473705/
504,504,Sun Jan 4 00:00:00 2015,NaN,NaN,Unknown,Feature Film,7,6.9,113.0,2011,"action, mystery, thriller",214477,2011-02-16,http://www.imdb.com/title/tt1401152/
505,505,Sun Jan 4 00:00:00 2015,NaN,NaN,Amores Perros,Feature Film,7,8.1,154.0,2000,"drama, thriller",178506,2000-05-14,http://www.imdb.com/title/tt0245712/
506,506,Sun Jan 4 00:00:00 2015,NaN,NaN,Serial (Bad) Weddings,Feature Film,7,7.0,97.0,2014,comedy,25603,2014-04-16,http://www.imdb.com/title/tt2800240/
507,507,Sun Jan 4 00:00:00 2015,NaN,NaN,Paths of Glory,Feature Film,8,8.5,88.0,1957,"drama, war",125510,1957-11-01,http://www.imdb.com/title/tt0050825/
508,508,Sun Jan 4 00:00:00 2015,NaN,NaN,Disturbia,Feature Film,7,6.9,105.0,2007,"drama, mystery, thriller",190202,2007-04-04,http://www.imdb.com/title/tt0486822/
509,509,Sun Jan 4 00:00:00 2015,NaN,NaN,The Team,Documentary,3,6.3,91.0,2014,"documentary, sport",1458,2014-11-11,http://www.imdb.com/title/tt4176326/

In [ ]:
#how to overwrite a row
imdb_rating.loc[481] = ['inser fields here']

In [21]:
#how to delete rows from df
imdb_rating_1 = imdb_rating.drop(imdb_rating.index[430:450])

In [22]:
imdb_rating_1

,position,created,modified,description,Title,Title type,You rated,IMDb Rating,Runtime (mins),Year,Genres,Num. Votes,Release Date (month/day/year),URL
1,1,Sat Dec 31 00:00:00 2016,NaN,NaN,Nightcrawler,Feature Film,8,7.9,117.0,2014,"crime, drama, thriller",311885,2014-09-05,http://www.imdb.com/title/tt2872718/
2,2,Fri Dec 30 00:00:00 2016,NaN,NaN,Ghost in the Shell 2.0,Feature Film,7,8.0,83.0,2008,"animation, action, crime, drama, sci_fi",10196,2008-07-12,http://www.imdb.com/title/tt1260502/
3,3,Fri Dec 30 00:00:00 2016,NaN,NaN,Game of Thrones,TV Series,10,9.5,56.0,2011,"adventure, drama, fantasy, romance",1095188,2011-04-17,http://www.imdb.com/title/tt0944947/
4,4,Fri Dec 30 00:00:00 2016,NaN,NaN,Charlie and the Chocolate Factory,Feature Film,6,6.7,115.0,2005,"adventure, comedy, family, fantasy",331238,2005-07-10,http://www.imdb.com/title/tt0367594/
5,5,Fri Dec 30 00:00:00 2016,NaN,NaN,Cars,Feature Film,7,7.2,117.0,2006,"animation, adventure, comedy, family, sport",272829,2006-03-14,http://www.imdb.com/title/tt0317219/
6,6,Fri Dec 30 00:00:00 2016,NaN,NaN,The Perks of Being a Wallflower,Feature Film,8,8.0,102.0,2012,"drama, romance",363872,2012-09-08,http://www.imdb.com/title/tt1659337/
7,7,Fri Dec 30 00:00:00 2016,NaN,NaN,"Honey, I Shrunk the Kids",Feature Film,6,6.3,93.0,1989,"adventure, comedy, family, sci_fi",110477,1989-06-23,http://www.imdb.com/title/tt0097523/
8,8,Fri Dec 30 00:00:00 2016,NaN,NaN,Jumanji,Feature Film,6,6.9,104.0,1995,"action, adventure, family, fantasy, thriller",215299,1995-12-15,http://www.imdb.com/title/tt0113497/
9,9,Fri Dec 30 00:00:00 2016,NaN,NaN,The Incredibles,Feature Film,8,8.0,115.0,2004,"animation, action, adventure, family",492831,2004-10-27,http://www.imdb.com/title/tt0317705/
10,10,Fri Dec 30 00:00:00 2016,NaN,NaN,E.T. the Extra-Terrestrial,Feature Film,7,7.9,115.0,1982,"family, sci_fi",290317,1982-05-26,http://www.imdb.com/title/tt0083866/
11,11,Fri Dec 30 00:00:00 2016,NaN,NaN,Madagascar,Feature Film,6,6.9,86.0,2005,"animation, adventure, comedy, family",275812,2005-05-25,http://www.imdb.com/title/tt0351283/
12,12,Fri Dec 30 00:00:00 2016,NaN,NaN,Hook,Feature Film,6,6.7,142.0,1991,"adventure, comedy, family, fantasy",187300,1991-12-08,http://www.imdb.com/title/tt0102057/
13,13,Fri Dec 30 00:00:00 2016,NaN,NaN,Ratatouille,Feature Film,7,8.0,111.0,2007,"animation, comedy, family, fantasy",488257,2007-06-22,http://www.imdb.com/title/tt0382932/
14,14,Fri Dec 30 00:00:00 2016,NaN,NaN,Ghost in the Shell,Feature Film,7,8.0,83.0,1995,"animation, action, mystery, sci_fi, thriller",84608,1995-11-18,http://www.imdb.com/title/tt0113568/
15,15,Fri Dec 30 00:00:00 2016,NaN,NaN,Mrs. Doubtfire,Feature Film,6,6.9,125.0,1993,"comedy, drama, family",187345,1993-11-24,http://www.imdb.com/title/tt0107614/
16,16,Fri Dec 30 00:00:00 2016,NaN,NaN,Ice Age,Feature Film,8,7.6,81.0,2002,"animation, adventure, comedy, family",337365,2002-03-12,http://www.imdb.com/title/tt0268380/
17,17,Tue Dec 27 00:00:00 2016,NaN,NaN,Sicario,Feature Film,7,7.6,121.0,2015,"action, crime, drama, mystery, thriller",223005,2015-05-19,http://www.imdb.com/title/tt3397884/
18,18,Thu Dec 15 00:00:00 2016,NaN,NaN,Westworld,TV Series,8,9.1,60.0,2016,"drama, mystery, sci_fi, western",108687,2016-10-02,http://www.imdb.com/title/tt0475784/
19,19,Mon Dec 12 00:00:00 2016,NaN,NaN,10 Cloverfield Lane,Feature Film,9,7.3,104.0,2016,"drama, horror, mystery, sci_fi, thriller",161240,2016-03-08,http://www.imdb.com/title/tt1179933/
20,20,Sun Dec 11 00:00:00 2016,NaN,NaN,Veep,TV Series,7,8.1,28.0,2012,comedy,26761,2012-04-22,http://www.imdb.com/title/tt1759761/
21,21,Tue Nov 29 00:00:00 2016,NaN,NaN,Arrival,Feature Film,8,8.3,116.0,2016,"drama, mystery, sci_fi, thriller",103756,2016-09-01,http://www.imdb.com/title/tt2543164/
22,22,Fri Nov 25 00:00:00 2016,NaN,NaN,Ein Mann unter Verdacht,TV Movie,7,7.1,89.0,2016,crime,46,2016-06-24,http://www.imdb.com/title/tt5790504/
23,23,Tue Nov 8 00:00:00 2016,NaN,NaN,Halt and Catch Fire,TV Series,8,8.3,60.0,2014,drama,17185,2014-03-08,http://www.imdb.com/title/tt2543312/
24,24,Sun Nov 6 00:00:00 2016,NaN,NaN,Alien,Feature Film,9,8.5,117.0,1979,"horror, sci_fi",583893,1979-05-25,http://www.imdb.com/title/tt0078748/
25,25,Sat Nov 5 00:00:00 2016,NaN,NaN,The Neon Demon,Feature Film,4,6.3,118.0,2016,"horror, thriller",37285,2016-05-20,http://www.imdb.com/title/tt1974419/
26,26,Sat Nov 5 00:00:00 2016,NaN,NaN,X-Men: First Class,Feature Film,7,7.8,132.0,2011,"action, adventure, sci_fi",532310,2011-05-25,http://www.imdb.com/title/tt1270798/
27,27,Wed Nov 2 00:00:00 2016,NaN,NaN,The Accountant,Feature Film,8,7.5,128.0,2016,"action, crime, drama, thriller",72280,2016-10-10,http://www.imdb.com/title/tt2140479/
28,28,Sun Oct 23 00:00:00 2016,NaN,NaN,Black Mirror,TV Series,10,8.9,60.0,2011,"drama, sci_fi, thriller",93649,2011-12-04,http://www.imdb.com/title/tt2085059/
29,29,Sat Oct 22 00:00:00 2016,NaN,NaN,Apollo 13,Feature Film,7,7.6,140.0,1995,"adventure, drama, history",214407,1995-06-22,http://www.imdb.com/title/tt0112384/
30,30,Tue Oct 18 00:00:00 2016,NaN,NaN,X-Men: Apocalypse,Feature Film,7,7.1,144.0,2016,"action, adventure, sci_fi",231116,2016-05-09,http://www.imdb.com/title/tt3385516/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
480,480,Sun Jan 4 00:00:00 2015,NaN,NaN,The Girl with the Dragon Tattoo,Feature Film,7,7.8,152.0,2009,"crime, drama, mystery, thriller",178180,2009-02-27,http://www.imdb.com/title/tt1132620/
481,481,Sun Jan 4 00:00:00 2015,NaN,NaN,Panic Room,Feature Film,7,6.8,112.0,2002,"crime, drama, thriller",210938,2002-03-18,http://www.imdb.com/title/tt0258000/
482,482,Sun Jan 4 00:00:00 2015,NaN,NaN,Cube,Feature Film,9,7.3,90.0,1997,"drama, mystery, sci_fi, thriller",165317,1997-09-09,http://www.imdb.com/title/tt0123755/
483,483,Sun Jan 4 00:00:00 2015,NaN,NaN,Salt,Feature Film,6,6.4,100.0,2010,"action, crime, mystery, thriller",250555,2010-07-19,http://www.imdb.com/title/tt0944835/
484,484,Sun Jan 4 00:00:00 2015,NaN,NaN,Perfume: The Story of a Murderer,Feature Film,7,7.5,147.0,2006,"crime, drama, fantasy",194910,2006-09-07,http://www.imdb.com/title/tt0396171/
485,485,Sun Jan 4 00:00:00 2015,NaN,NaN,Sunshine,Feature Film,8,7.3,107.0,2007,"adventure, sci_fi, thriller",194559,2007-03-23,http://www.imdb.com/title/tt0448134/
486,486,Sun Jan 4 00:00:00 2015,NaN,NaN,Unfaithful,Feature Film,6,6.7,124.0,2002,"drama, thriller",64567,2002-05-08,http://www.imdb.com/title/tt0250797/
487,487,Sun Jan 4 00:00:00 2015,NaN,NaN,The Others,Feature Film,6,7.6,101.0,2001,"horror, mystery, thriller",275571,2001-08-02,http://www.imdb.com/title/tt0230600/
488,488,Sun Jan 4 00:00:00 2015,NaN,NaN,Primal Fear,Feature Film,9,7.7,129.0,1996,"crime, drama, mystery, thriller",136381,1996-04-03,http://www.imdb.com/title/tt0117381/
489,489,Sun Jan 4 00:00:00 2015,NaN,NaN,Contagion,Feature Film,5,6.6,106.0,2011,"drama, thriller",183833,2011-09-03,http://www.imdb.com/title/tt1598778/
490,490,Sun Jan 4 00:00:00 2015,NaN,NaN,Vicky Cristina Barcelona,Feature Film,6,7.2,96.0,2008,"drama, romance",203201,2008-05-17,http://www.imdb.com/title/tt0497465/
491,491,Sun Jan 4 00:00:00 2015,NaN,NaN,Identity,Feature Film,8,7.3,90.0,2003,"mystery, thriller",182644,2003-04-23,http://www.imdb.com/title/tt0309698/
492,492,Sun Jan 4 00:00:00 2015,NaN,NaN,Mission: Impossible,Feature Film,7,7.1,110.0,1996,"action, adventure, thriller",308458,1996-05-20,http://www.imdb.com/title/tt0117060/
493,493,Sun Jan 4 00:00:00 2015,NaN,NaN,The Raid: Redemption,Feature Film,4,7.6,101.0,2011,"action, crime, thriller",152529,2011-09-08,http://www.imdb.com/title/tt1899353/
494,494,Sun Jan 4 00:00:00 2015,NaN,NaN,Life of Brian,Feature Film,7,8.1,94.0,1979,comedy,280885,1979-08-17,http://www.imdb.com/title/tt0079470/
495,495,Sun Jan 4 00:00:00 2015,NaN,NaN,The Naked Gun: From the Files of Police Squad!,Feature Film,7,7.6,85.0,1988,"comedy, crime",117912,1988-12-02,http://www.imdb.com/title/tt0095705/
496,496,Sun Jan 4 00:00:00 2015,NaN,NaN,Rosemary's Baby,Feature Film,8,8.0,137.0,1968,"drama, horror",144870,1968-06-12,http://www.imdb.com/title/tt0063522/
497,497,Sun Jan 4 00:00:00 2015,NaN,NaN,Side Effects,Feature Film,7,7.1,106.0,2013,"crime, drama, thriller",151436,2013-01-31,http://www.imdb.com/title/tt2053463/
498,498,Sun Jan 4 00:00:00 2015,NaN,NaN,Red Eye,Feature Film,6,6.5,85.0,2005,"mystery, thriller",95793,2005-08-04,http://www.imdb.com/title/tt0421239/
499,499,Sun Jan 4 00:00:00 2015,NaN,NaN,Terminator 3: Rise of the Machines,Feature Film,6,6.4,109.0,2003,"action, sci_fi",312324,2003-06-30,http://www.imdb.com/title/tt0181852/
500,500,Sun Jan 4 00:00:00 2015,NaN,NaN,Phone Booth,Feature Film,9,7.1,81.0,2002,"crime, thriller",213136,2002-09-10,http://www.imdb.com/title/tt0183649/
501,501,Sun Jan 4 00:00:00 2015,NaN,NaN,Adaptation.,Feature Film,8,7.7,114.0,2002,"comedy, drama",146482,2002-12-06,http://www.imdb.com/title/tt0268126/
502,502,Sun Jan 4 00:00:00 2015,NaN,NaN,Final Destination,Feature Film,6,6.7,98.0,2000,"horror, thriller",185492,2000-03-16,http://www.imdb.com/title/tt0195714/
503,503,Sun Jan 4 00:00:00 2015,NaN,NaN,State of Play,Feature Film,7,7.1,127.0,2009,"crime, drama, mystery, thriller",115342,2009-04-17,http://www.imdb.com/title/tt0473705/
504,504,Sun Jan 4 00:00:00 2015,NaN,NaN,Unknown,Feature Film,7,6.9,113.0,2011,"action, mystery, thriller",214477,2011-02-16,http://www.imdb.com/title/tt1401152/
505,505,Sun Jan 4 00:00:00 2015,NaN,NaN,Amores Perros,Feature Film,7,8.1,154.0,2000,"drama, thriller",178506,2000-05-14,http://www.imdb.com/title/tt0245712/
506,506,Sun Jan 4 00:00:00 2015,NaN,NaN,Serial (Bad) Weddings,Feature Film,7,7.0,97.0,2014,comedy,25603,2014-04-16,http://www.imdb.com/title/tt2800240/
507,507,Sun Jan 4 00:00:00 2015,NaN,NaN,Paths of Glory,Feature Film,8,8.5,88.0,1957,"drama, war",125510,1957-11-01,http://www.imdb.com/title/tt0050825/
508,508,Sun Jan 4 00:00:00 2015,NaN,NaN,Disturbia,Feature Film,7,6.9,105.0,2007,"drama, mystery, thriller",190202,2007-04-04,http://www.imdb.com/title/tt0486822/
509,509,Sun Jan 4 00:00:00 2015,NaN,NaN,The Team,Documentary,3,6.3,91.0,2014,"documentary, sport",1458,2014-11-11,http://www.imdb.com/title/tt4176326/